// -*- Mode: typescript; typescript-indent-level: 2; -*-
import { HagaKeyword } from './toolchain/hagaKeyword';
import { HagaSweet, HagaSweetString, HagaSweetTargetRsvgConvert } from './toolchain/hagaSweet'

const INDIR_PUBLIC  : HagaSweetString = [HagaKeyword.CURRENT_INPUT_DIR,  '/public'];
const OUTDIR_TSC    : HagaSweetString = [HagaKeyword.CURRENT_OUTPUT_DIR, '/tsc'];
const OUTDIR_CPP    : HagaSweetString = [HagaKeyword.CURRENT_OUTPUT_DIR, '/cpp'];
const OUTDIR_PUBLIC : HagaSweetString = [HagaKeyword.CURRENT_OUTPUT_DIR, '/public'];
const OUTDIR_DEPLOY : HagaSweetString = [HagaKeyword.CURRENT_OUTPUT_DIR, '/deploy'];

export default HagaSweet.eatSugar({
  targets: [
    {
      type: 'tsc',
      inputs: [
        'public/burger.ts',
        'public/language.ts',
      ],
      outputDir: OUTDIR_TSC,
    },
    {
      type: 'minify',
      inputs: [
        'burger.js',
        'language.js',
      ],
      inputDir: OUTDIR_TSC,
      outputDir: OUTDIR_PUBLIC,
    },
    {
      type: 'cpps',
      inputs: [
        'index.css.in',
        'index.html.in',
        'travel.css.in',
        'travel.html.in',
        'hotels.css.in',
        'hotels.html.in',
        'rsvp.html.in',
      ],
      inputDir: INDIR_PUBLIC,
      outputDir: OUTDIR_CPP,
      defines: ['USE_UNDER_CONSTRUCTION=1'],
    },
    {
      type: 'minify',
      inputs: [
        'index.css',
        'index.html',
        'travel.css',
        'travel.html',
        'hotels.css',
        'hotels.html',
        'rsvp.html',
      ],
      inputDir: OUTDIR_CPP,
      outputDir: OUTDIR_PUBLIC,
    },
    ...[16, 32, 48, 96, 128, 180, 192].map((d: number): HagaSweetTargetRsvgConvert => {
      return {
        type: 'rsvg-convert',
        input:  'public/favicon.svg',
        output: `public/favicon-${d}x${d}.png`,
        args: ['-w', `${d}`, '-h', `${d}`],
      }
    }),
    {
      type: 'magick',
      input:  [HagaKeyword.CURRENT_OUTPUT_DIR, '/public/favicon-192x192.png'],
      output: `public/favicon.ico`,
      args: ['-background', 'none', '-define', 'icon:auto-resize=16,32,48'],
    },
    {
      type: 'magick',
      input: 'design/butterfly-dark.png',
      output: 'public/butterfly-dark.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/flowers1-dark.png',
      output: 'public/flowers1-dark.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/flowers1-light.png',
      output: 'public/flowers1-light.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/flowers2-dark.png',
      output: 'public/flowers2-dark.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/flowers3-dark.png',
      output: 'public/flowers3-dark.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/rose-light.png',
      output: 'public/rose-light.webp',
      args: ['-resize', '50%'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408546.jpg',
      output: 'public/londonmemory1.jpeg',
      args: ['-resize', '25%', '-gravity', 'center', '-crop', '90%x100%+0+0', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408612.jpg',
      output: 'public/londonmemory2.jpeg',
      args: ['-resize', '25%', '-gravity', 'center', '-crop', '90%x100%+0+0', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408010.jpg',
      output: 'public/londonmemory3.jpeg',
      args: ['-resize', '12.5%', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7407434.jpg',
      output: 'public/londonmemory4.jpeg',
      args: ['-resize', '25%', '-quality', '95'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7407844.jpg',
      output: 'public/londonmemory5.jpeg',
      args: ['-resize', '12.5%', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408103-5-4.jpg',
      output: 'public/londonmemory6.jpeg',
      args: ['-resize', '12.5%', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408313.jpg',
      output: 'public/londonmemory7.jpeg',
      args: ['-resize', '12.5%', '-quality', '90'],
    },
    {
      type: 'magick',
      input: 'design/20260511-A7408366.jpg',
      output: 'public/londonmemory8.jpeg',
      args: [
        '-resize', '12.5%',
        '-crop', '100%x78%+0+0',
        '-gravity', 'west',
        '-crop', '95%x100%+0+0',
        '-gravity', 'east',
        '-crop', '83%x100%+0+0',
        '-quality', '90',
      ],
    },
    {
      type: 'copy',
      inputs: [
        'public/.htaccess',
        'public/favicon.svg',
        'public/placeholder3.jpeg',
        'public/travel-stamp-image.jpeg',
        'public/hotels-hero.jpeg',
        'public/Aileron.woff2',
        'public/AileronBold.woff2',
        'public/NewIconSerifRegular.woff2',
        'public/PinyonScript.woff2',
      ],
    },
    {
      type: 'rsync',
      name: 'deploy',
      srcDir: OUTDIR_PUBLIC,
      configTemplate: {
        dstDir: OUTDIR_DEPLOY,
      },
      config: 'deploy.json',
      inputs: [
        '.htaccess',
        'burger.js',
        'favicon.svg',
        'favicon.ico',
        'favicon-16x16.png',
        'favicon-32x32.png',
        'favicon-48x48.png',
        'favicon-96x96.png',
        'favicon-128x128.png',
        'favicon-180x180.png',
        'favicon-192x192.png',
        'index.css',
        'index.html',
        'travel.css',
        'travel.html',
        'hotels.css',
        'hotels.html',
        'rsvp.html',
        'language.js',
        'butterfly-dark.webp',
        'flowers1-dark.webp',
        'flowers1-light.webp',
        'flowers2-dark.webp',
        'flowers3-dark.webp',
        'rose-light.webp',
        'placeholder3.jpeg',
        'londonmemory1.jpeg',
        'londonmemory2.jpeg',
        'londonmemory3.jpeg',
        'londonmemory4.jpeg',
        'londonmemory5.jpeg',
        'londonmemory6.jpeg',
        'londonmemory7.jpeg',
        'londonmemory8.jpeg',
        'travel-stamp-image.jpeg',
        'hotels-hero.jpeg',
        'Aileron.woff2',
        'AileronBold.woff2',
        'NewIconSerifRegular.woff2',
        'PinyonScript.woff2',
      ],
    },
  ],
});
